name: Deploy Static Site to Modal

on:
  push:
    branches:
      - main
    paths:
      - 'workshop_4_5_6/modal/static_site.py'
      - 'workshop_4_5_6/modal/data_viewers/**'
      - 'workshop_4_5_6/modal/data/**'
      - '.github/workflows/static-site-deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install Modal and dependencies
        run: |
          pip install modal fastapi uvicorn

          - name: Configure Modal token
          run: |
            modal token set --token-id ${{ secrets.MODAL_TOKEN_ID }} --token-secret ${{ secrets.MODAL_TOKEN_SECRET }}
        env:
          MODAL_TOKEN_ID: ${{ secrets.MODAL_TOKEN_ID }}
          MODAL_TOKEN_SECRET: ${{ secrets.MODAL_TOKEN_SECRET }}

      - name: Deploy static site to Modal
        run: |
          cd workshop_4_5_6/modal
          modal deploy static_site.py